name: Validate item data

on:
  pull_request:
    paths:
      - "items/**/*.yml"
      - "schemas/**/*"
      - ".github/workflows/**/*"
      - "builder/**/*"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pipenv

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install python dependencies
        run: pipenv sync

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install ajv-cli
        run: |
          npm install -g ajv-cli

      - name: Run validation and composing script
        run: |
          pipenv run python builder/run.py \
            -i items -c consumables \
            -is schemas/single-item.schema.json -csg 'schemas/common/*.schema.json' \
            -o build/item-data.json -co github-pr-comment.txt

      - name: Upload compiled item data as build artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact-item-data
        if: ${{ success() }}
        with:
          name: item-data
          path: build/item-data.json
          if-no-files-found: error

      - name: Check if PR comment exists
        id: mark-pr-comment-exists
        if: ${{ always() && github.event_name == 'pull_request' }}
        run: |
          [[ -f github-pr-comment.txt ]] && echo "pr-comment-exists=true" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Upload github PR comment as build artifact
        id: upload-artifact-pr-comment
        if: ${{ always() && steps.mark-pr-comment-exists.outputs.pr-comment-exists == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-comment
          path: github-pr-comment.txt
          if-no-files-found: error
